on:
  issues:
    types: 
      - created

jobs:
  label_issue:
    runs-on: ubuntu-latest
  steps:
    -env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_URL: ${{ github.event.issue.html_url }}
      ISSUE_OBJ: ${{ github.event.issue }}
    run: |
      echo "$ISSUE_OBJ"
      gh issue edit $ISSUE_URL --add-label "shubh"